### ISSUE TITLE
Hangs Forever

### ISSUE THREAD

**Issue by joshuafhiggins** [DeadZoneLuna/uSource#1]
Trying to load any model causes this. It spikes in memory and then goes down to being idle but the task isn't responding but still using 30% of my CPU. Haven't even tried maps.

**Comment by DeadZoneLuna** [comment]
Sorry for the late reply!

Well, i think this version Importer (new version is still WIP) tryied find model, but if model not find, it tried load "ERROR" model placeholder, but if not find too, you got "for loop" bug x3 (for materials / textures too, i forgot make it optional)

For fix, open script "StudioMdlLoader.cs" and go down to "76" line & replace this:

```csharp
            if (!File.Exists(OpenPath + ".mdl"))
            {
                Debug.Log(String.Format("{0}: File not found", ModelName + ".mdl"));
                return Load("error");
                //return ModelObject.transform;
            }
```

to this:

```csharp
            if (!File.Exists(OpenPath + ".mdl"))
            {
                Debug.Log(String.Format("{0}: File not found", ModelName + ".mdl"));
                return ModelObject.transform;
            }
```

Same thing need fix in "TextureLoader.cs" & "MaterialLoader.cs"

for "TextureLoader.cs", go down to "29" line & replace this:

```csharp
            if (string.IsNullOrEmpty(Path))
            {
                if (AltTexture != null)
                    return Load(AltTexture);

                Debug.Log(String.Format("{0}: File not found", MainTexture + ".vtf"));
                return Load("debug/debugempty", null);
                //return null;
            }
```

to this:

```csharp
            if (string.IsNullOrEmpty(Path))
            {
                if (AltTexture != null)
                    return Load(AltTexture);

                Debug.Log(String.Format("{0}: File not found", MainTexture + ".vtf"));
                return null;
            }
```

and in "MaterialLoader.cs", go down to "52" line & replace this:
```csharp
            if (String.IsNullOrEmpty(Path))
            {
                Debug.Log(String.Format("{0}: File not found", MaterialName + ".vmt"));
                return Load("debug/debugempty");
            }
```

to this:

```csharp
            if (String.IsNullOrEmpty(Path))
            {
                Debug.Log(String.Format("{0}: File not found", MaterialName + ".vmt"));
                return null;
            }
```

i hope it fixed "for loop" bug for you :^)

If you have questions & want fast answers, DM me in discord: @DeadZoneGarry3474 or [Steam](http://steamcommunity.com/profiles/76561198121485860) or [VK](https://vk.com/id160454360)
