### ISSUE TITLE
Can't load bsp maps of counter strike 1.6

### ISSUE THREAD

**Issue by aidin0181** [DeadZoneLuna/uSource#2]
Hi, the project wont be able to load the maps for counter strike 1.6. example map is de_dust2.bsp
here is the error message:

FileLoadException: de_dust2: File signature does not match 'VBSP'
Engine.Source.BspLoader.Load (System.String BSPName) (at Assets/Unity_Source_Engine_Importer/Core/BSP/BspLoader.cs:52)
Engine.Source.ConfigurationLoaderEditor.OnInspectorGUI () (at Assets/Unity_Source_Engine_Importer/Core/ConfigLoader.cs:20)
UnityEditor.InspectorWindow.DoOnInspectorGUI (System.Boolean rebuildOptimizedGUIBlock, UnityEditor.Editor editor, System.Boolean wasVisible, UnityEngine.Rect& contentRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1647)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at C:/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)

**Comment by SolarisBravo** [comment]
Counter-Strike 1.6 is not a Source Engine game, and does not use the Source Engine .bsp format.

**Comment by DeadZoneLuna** [comment]
@SolarisBravo absolutely right, the project is currently working only with Source Engine resources, in the future it will be possible to add support for GoldSource.

@aidin0181 
You're can try another project like this: [unityHalf-life](https://github.com/thelivewire/unityHalf-life)
