### ISSUE TITLE
Loader credits stacked ontop of settings and the Lightmapped Generic shader turns everything black

### ISSUE THREAD

**Issue by Johnny-Ghost-PIE** [DeadZoneLuna/uSource#3]
I decided to import uSource into Unity 2019 LTS to port some maps from Gmod into it, and when I click on the loader window or use the loader script, the special thanks credits end up stacked on top of the settings to import the maps. I also have an issue where any material I try to give the lightmapped generic shader to turns pitch black. Is this a compatibility issue, or is it some other problem? I'd like to be able to use uSource with Unity 2019 since a game I play uses that build of the Unity engine.
![Untitled](https://user-images.githubusercontent.com/51310201/129297189-da1d409b-04b8-4062-b156-b5f61acac943.png)

**Comment by DeadZoneLuna** [comment]
Fixed in ce3edf9
